searchPath=/liquibase

changeLogFile=project/changelog/db.changelog-master.sql

url=jdbc:oracle:thin:@oracle-db:1521/FREEPDB1
username=DBVC
password=Dbvc123

driver=oracle.jdbc.OracleDriver
classpath=/liquibase/drivers/ojdbc11.jar