spring.application.name=backend

server.port=8085

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
spring.datasource.username=DBVC
spring.datasource.password=Dbvc123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=never
dbvc.project-root=..

dbvc.liquibase.changelog-path=../liquibase/changelog/db.changelog-master.sql
dbvc.execution-worker.fixed-delay-ms=10000
dbvc.environment.dev.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
dbvc.environment.dev.username=DBVC_DEV
dbvc.environment.dev.password=Dev123

dbvc.environment.test.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
dbvc.environment.test.username=DBVC_TEST
dbvc.environment.test.password=Test123

dbvc.environment.prod.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
dbvc.environment.prod.username=DBVC_PROD
dbvc.environment.prod.password=Prod123
dbvc.jwt.secret=change-this-local-development-secret-key-please-keep-it-long
dbvc.jwt.issuer=dbvc-platform
dbvc.jwt.expiration-minutes=480

dbvc.auth.default-admin-username=admin
dbvc.auth.default-admin-password=Admin123!